import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { registerSW } from "virtual:pwa-register";
import { switchTestUser, getTestUsersForSelector, simulateJoinRequest, clearTestData, logTestHelperInfo } from "./lib/testUsers";

// automatically register the service worker generated by vite-plugin-pwa
const updateSW = registerSW({
  onUpdate() {
    if (confirm("New content is available, reload to update?")) {
      window.location.reload();
    }
  }
});

// Expose test helper functions to window for console access
// Usage: Open DevTools console and call these functions directly
if (import.meta.env.DEV) {
  (window as any).testHelper = {
    switchTestUser,
    getTestUsersForSelector,
    simulateJoinRequest,
    clearTestData,
    logTestHelperInfo
  };
  console.log("✨ CodeMate Test Helper loaded! Type testHelper.logTestHelperInfo() for usage");
}

createRoot(document.getElementById("root")!).render(<App />);
